export const global_variables = {
    debounceTime: 1000,
    passMark: 80,
    writingPassMark: 60,
    examWPassmark: 60,
    examPassMark: 80,
    GrammarTime: 1860,
    ReadingTime: 660,
    WritingTime: 660,
    ConversationTime: 660,
    PreIntermediatePreTestPass: 70,
    IntermediatePreTestPass: 70,
    UpperIntermediatePreTestPass: 60,
    ConfidentPreTestPass: 60,
};
