declare module '@env' {
    export const API_BASE_URL_RLS: string;
    export const API_BASE_URL_RLS_2: string;
    export const API_BASE_URL_DEV_IOS: string;
    export const API_BASE_URL_DEV_ANDROID: string;
    export const API_BASE_URL_DEV_ANDROID_P: string;
    export const SECURE_STORAGE_NAME: string;
    export const SECURE_STORAGE_USER_INFO: string;
    export const SECURE_STORAGE_SCHEDULE_INFO: string;
    export const SECURE_STORAGE_VOICE_INFO: string;
    export const SECURE_STORAGE_CREDIT_CARD_INFO: string;
    export const SECURE_STORAGE_GLOSSARY: string;
    export const SECURE_STORAGE_SPEECH_CONTROLLER: string;
    export const SECURE_STORAGE_ADMIN_DATA: string;
    export const SECURE_STORAGE_VOCABULARY_DATA: string;
    export const SECURE_STORAGE_CLESSON_DATA: string;
    export const SECURE_STORAGE_INIT_INTEREST: string;
    export const GOOGLE_TTS_LINK: string;
    export const GOOGLE_TRANSLATE_LINK: string;
    export const GOOGLE_STT_LINK: string;
}
